"""Generate LaTeX tables, pgfplots data and numeric macros for paper/main.tex
from committed raw results. No sampling is performed; closed-form curves are
computed with p5compat.analytic on the regenerated (digest-checked) v1 rows.

Usage: python3 scripts/make_paper_assets.py
Outputs: paper/generated/*.tex, paper/generated/*.dat
"""

import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from p5compat import analytic as an  # noqa: E402
from p5compat import samplers as sp  # noqa: E402
from p5compat import stats as st  # noqa: E402
from reanalyse_v1 import rows_for  # noqa: E402

OUT = os.path.join(ROOT, "paper", "generated")
V1 = os.path.join(ROOT, "results", "raw", "p5_first_run_v1_test")
E8 = os.path.join(ROOT, "results", "raw", "p5_e8_exact_v1")
RE = os.path.join(ROOT, "results", "reanalysis_v1")

HEADER = "% AUTO-GENERATED by scripts/make_paper_assets.py from committed raw results. Do not edit by hand.\n"


def load(p):
    with open(p) as f:
        return json.load(f)


def k3(v, nd=2):
    """value x 1e3 formatted."""
    return "--" if v is None else f"{1e3 * v:.{nd}f}"


def ci3(b, nd=2):
    if b is None or b.get("mean") is None:
        return "--"
    return f"{k3(b['mean'], nd)} [{k3(b['lo'], nd)}, {k3(b['hi'], nd)}]"


def pv(p):
    return "--" if p is None else f"{p:.3f}"


def tt(name):
    return "\\texttt{" + name.replace("_", "\\_") + "}"


def macro(name, value):
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def main():
    os.makedirs(OUT, exist_ok=True)
    cfg = load(os.path.join(ROOT, "configs", "p5_first_run.json"))
    man = load(os.path.join(V1, "manifest.json"))
    summ = load(os.path.join(V1, "summary.json"))
    pvo = load(os.path.join(RE, "predicted_vs_observed.json"))
    gaps = load(os.path.join(RE, "population_gaps.json"))
    znull = load(os.path.join(RE, "z_null_check.json"))
    e8 = load(os.path.join(E8, "summary.json"))
    e8man = load(os.path.join(E8, "manifest.json"))
    pred = {(r["exp"], r["cond"]): r for r in pvo}

    def c(eid, cid):
        return summ[eid]["conditions"][cid]

    # ------------------------------------------------------------------ numbers
    n = HEADER
    e1 = c("P5-E1-NULL", "exact_sequential")
    n += macro("numNullP", pv(e1["target"]["p_sign_flip"]))
    n += macro("numNullPjoint", pv(e1["joint"]["p_sign_flip"]))
    n += macro("numMarkovNullP", pv(c("P5-E4-MARKOV", "exact_sequential")["target"]["p_sign_flip"]))
    reps = summ["P5-E1-NULL-REPS"]
    n += macro("numRepRejT", f"{reps['fpr_target']['k']}/{reps['fpr_target']['n']}")
    n += macro("numRepRejJ", f"{reps['fpr_joint']['k']}/{reps['fpr_joint']['n']}")
    rb = znull["replicates"]
    n += macro("numRepCPlo", f"{rb['cp_two_sided_target']['lo']:.3f}")
    n += macro("numRepCPhi", f"{rb['cp_two_sided_target']['hi']:.3f}")
    n += macro("numRepZsd", f"{rb['sd_z_target']:.2f}")
    n += macro("numRepZsdLo", f"{rb['sd_ci_target'][0]:.2f}")
    n += macro("numRepZsdHi", f"{rb['sd_ci_target'][1]:.2f}")
    sdt = [z["signflip_t_sd"] for z in znull["per_condition"]]
    q95 = [z["signflip_t_q95"] for z in znull["per_condition"]]
    ku = [z["kurtosis_d"] for z in znull["per_condition"]]
    n += macro("numZflipSdMin", f"{min(sdt):.3f}")
    n += macro("numZflipSdMax", f"{max(sdt):.3f}")
    n += macro("numZflipQmin", f"{min(q95):.2f}")
    n += macro("numZflipQmax", f"{max(q95):.2f}")
    n += macro("numKurtMin", f"{min(ku):.1f}")
    n += macro("numKurtMax", f"{max(ku):.1f}")
    n += macro("numFloorM", f"{e1['target']['ed_floor']['mean']:.4f}")
    cb = c("P5-E3-COLLAPSE", "collapse_both")
    crps_exact = e1["crps_ref"]["mean"]
    crps_coll = cb["crps_ref"]["mean"]
    n += macro("numCRPSexact", f"{crps_exact:.3f}")
    n += macro("numCRPScollapse", f"{crps_coll:.3f}")
    n += macro("numCRPScollapsePct", f"{100 * (crps_coll / crps_exact - 1):.1f}")
    n += macro("numCRPScollapseTheoryPct", f"{100 * (math.sqrt(2) - 1):.1f}")
    ci = c("P5-E3-COLLAPSE", "collapse_intermediate")
    n += macro("numCollIntD", f"{ci['target']['d']['mean']:.4f}")
    n += macro("numCollIntDiv", f"{ci['div_cmp']['mean']:.2f}")
    n += macro("numCollIntMSE", f"{ci['paired_mse_over_tau2']['mean']:.2f}")
    n += macro("numExactMSE", f"{e1['paired_mse_over_tau2']['mean']:.2f}")
    oi = c("P5-E4-INTERMEDIATE", "observed_intermediate")
    ob = oi["crps_diff_cmp_minus_ref"]
    n += macro("numObsIntCRPS", f"{ob['mean']:.3f} [{ob['lo']:.3f}, {ob['hi']:.3f}]")
    corr_p = [c("P5-E2-CHECKER", f"corr_scale_{s}")["target"]["p_sign_flip"] for s in ("-1", "0", "0.5")]
    n += macro("numCorrPmin", pv(min(corr_p)))
    n += macro("numCorrPmax", pv(max(corr_p)))
    zt = [abs(r["z_obs_minus_pred"]) for r in pvo if r.get("z_obs_minus_pred") is not None]
    zj = [abs(r["zJ_obs_minus_pred"]) for r in pvo if r.get("zJ_obs_minus_pred") is not None]
    n += macro("numPredCellsT", str(len(zt)))
    n += macro("numPredCellsJ", str(len(zj)))
    n += macro("numPredZmaxT", f"{max(zt):.2f}")
    n += macro("numPredZmaxJ", f"{max(zj):.2f}")
    g = {x["cond"]: x for x in gaps}
    n += macro("numGapPrior", f"{g['exact_flow_limit']['pop_D_compared_vs_reference']:.5f}")
    for w, key in (("0.5", "cfg_0.5_seq"), ("1", "cfg_1_seq"), ("2", "cfg_2_seq"), ("4", "cfg_4_seq")):
        n += macro("numGapCFG" + {"0.5": "Half", "1": "One", "2": "Two", "4": "Four"}[w],
                   f"{g[key]['pop_D_compared_vs_reference']:.3f}")
    n += macro("numGapEulerSixtyFour", f"{g['euler_64_seq']['pop_D_compared_vs_reference']:.5f}")
    n += macro("numGapEulerFour", f"{g['euler_4_seq']['pop_D_compared_vs_reference']:.5f}")
    n += macro("numBiasEulerSixteen", f"{g['euler_16_direct_vs_exact']['pop_D_compared_vs_reference']:.4f}")
    n += macro("numBiasCFGFour", f"{g['cfg_4_direct_vs_exact']['pop_D_compared_vs_reference']:.3f}")
    n += macro("numBiasCFGOne", f"{g['cfg_1_direct_vs_exact']['pop_D_compared_vs_reference']:.4f}")
    se_e6 = [c("P5-E6-SOLVER", k)["target"]["d"]["se"] for k in ("euler_8_seq", "euler_16_seq", "euler_32_seq", "euler_64_seq")]
    n += macro("numSEsolverMin", f"{min(se_e6):.4f}")
    n += macro("numSEsolverMax", f"{max(se_e6):.4f}")
    n += macro("numRuntimeVone", f"{man['total_seconds']:.1f}")
    n += macro("numRuntimeEeight", f"{e8man['total_seconds']:.1f}")
    cells = e8["C"]["cells"]
    nul = cells["exact_sequential|target"]["detector"]
    n += macro("numEeightNullK", f"{nul['k']}/{nul['n']}")
    n += macro("numEeightNullLo", f"{nul['cp_lower_95_one_sided']:.3f}")
    n += macro("numEeightNullHi", f"{nul['cp_upper_95_one_sided']:.3f}")
    ms = cells["mean_shift_2.0|target"]["detector"]
    n += macro("numEeightShiftK", f"{ms['k']}/{ms['n']}")
    n += macro("numEeightShiftLo", f"{ms['cp_lower_95_one_sided']:.3f}")
    n += macro("numEeightAdatasets", str(e8["A"]["n_datasets"]))
    n += macro("numEeightBdatasets", str(e8["B"]["n_datasets"]))
    n += macro("numEeightBminP", f"{e8['B']['min_p_mc']:.4f}")
    calib = load(os.path.join(ROOT, "configs", "p5_e8_calib_v2.json"))
    n += macro("numCalibCPUmin", f"{calib['resource_estimate']['estimated_cpu_minutes']:.0f}")
    with open(os.path.join(OUT, "numbers.tex"), "w") as f:
        f.write(n)

    # ------------------------------------------------------------------ re-aggregation from raw
    def raw_rows(eid, cid):
        with open(os.path.join(V1, f"{eid}.jsonl")) as fh:
            return {r["i"]: r for r in map(json.loads, fh) if r["cond"] == cid}

    ex_rows = raw_rows("P5-E1-NULL", "exact_sequential")
    cb_rows = raw_rows("P5-E3-COLLAPSE", "collapse_both")
    collapse_vs_exact = st.mean_ci([cb_rows[i]["crps_cmp"] - ex_rows[i]["crps_ref"] for i in sorted(ex_rows)])
    n_extra = macro("numCollapseVsExactCRPS", f"{collapse_vs_exact['mean']:.3f} [{collapse_vs_exact['lo']:.3f}, {collapse_vs_exact['hi']:.3f}]")
    with open(os.path.join(OUT, "numbers.tex"), "a") as f:
        f.write(n_extra)

    # ------------------------------------------------------------------ Table: controls
    rows = [
        ("P5-E1-NULL", "exact_sequential", "Exact sequential (null)"),
        ("P5-E2-CHECKER", "mean_shift_0.05", "Mean shift $0.05\\tau$"),
        ("P5-E2-CHECKER", "mean_shift_0.1", "Mean shift $0.1\\tau$"),
        ("P5-E2-CHECKER", "mean_shift_0.5", "Mean shift $0.5\\tau$"),
        ("P5-E2-CHECKER", "var_ratio_0.8", "Variance ratio 0.8"),
        ("P5-E2-CHECKER", "var_ratio_1.1", "Variance ratio 1.1"),
        ("P5-E2-CHECKER", "var_ratio_1.5", "Variance ratio 1.5"),
        ("P5-E2-CHECKER", "corr_scale_-1", "Corr.\\ scale $-1$ (target exact)"),
        ("P5-E2-CHECKER", "corr_scale_0.5", "Corr.\\ scale $0.5$ (target exact)"),
        ("P5-E3-COLLAPSE", "collapse_both", "Collapse, both branches"),
        ("P5-E3-COLLAPSE", "collapse_intermediate", "Collapse, intermediate only"),
        ("P5-E4-INTERMEDIATE", "observed_intermediate", "Observed intermediate"),
        ("P5-E4-INTERMEDIATE", "chain_drop_x", "Chain $z\\mid y$ (non-Markov)"),
        ("P5-E4-MARKOV", "chain_drop_x", "Chain $z\\mid y$ (Markov)"),
    ]
    t = HEADER + "\\begin{tabular}{lrrrrrr}\n\\toprule\n"
    t += ("Condition & $\\bar d\\times10^3$ [95\\% CI] & $p_T$ & $\\bar d_J\\times10^3$ & $p_J$ & "
          "$\\Delta\\mathrm{CRPS}\\times10^3$ [95\\% CI] & sd ratio \\\\\n\\midrule\n")
    for eid, cid, label in rows:
        s = c(eid, cid)
        j = s["joint"]
        crps_cell = ci3(s["crps_diff_cmp_minus_ref"], 1)
        if cid == "collapse_both":
            # re-aggregated from raw: paired by example against the exact direct sampler (same rows)
            crps_cell = ci3(collapse_vs_exact, 1) + "$^\\dagger$"
        t += (f"{label} & {ci3(s['target']['d'])} & {pv(s['target']['p_sign_flip'])} & "
              f"{'--' if j is None else k3(j['dJ']['mean'])} & {'--' if j is None else pv(j['p_sign_flip'])} & "
              f"{crps_cell} & {s['div_cmp']['mean']:.2f} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_controls.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Table: numerical components
    nrows = [
        ("P5-E6-SOLVER", "euler_2_seq", "Euler, 2 steps"),
        ("P5-E6-SOLVER", "euler_4_seq", "Euler, 4 steps"),
        ("P5-E6-SOLVER", "euler_8_seq", "Euler, 8 steps"),
        ("P5-E6-SOLVER", "euler_64_seq", "Euler, 64 steps"),
        ("P5-E6-SOLVER", "heun_4_seq", "Heun, 4 steps"),
        ("P5-E6-SOLVER", "heun_16_seq", "Heun, 16 steps"),
        ("P5-E7-CFG", "cfg_0.5_seq", "Euler 64, $w=0.5$"),
        ("P5-E7-CFG", "cfg_1_seq", "Euler 64, $w=1$"),
        ("P5-E7-CFG", "cfg_4_seq", "Euler 64, $w=4$"),
    ]
    t = HEADER + "\\begin{tabular}{lrrrr}\n\\toprule\n"
    t += ("Sampler (both branches) & $D_{\\mathrm{pop}}\\times10^3$ & $\\mathbb{E}[d]\\times10^3$ & "
          "$\\bar d\\times10^3$ [95\\% CI] & $p_T$ \\\\\n\\midrule\n")
    for eid, cid, label in nrows:
        s = c(eid, cid)
        r = pred[(eid, cid)]
        t += (f"{label} & {k3(r['pop_D_target'], 3)} & {k3(r['pred_E_d'], 3)} & {ci3(s['target']['d'])} & "
              f"{pv(s['target']['p_sign_flip'])} \\\\\n")
    gl = g["exact_flow_limit"]
    t += (f"Exact flow, $N\\to\\infty$ & {k3(gl['pop_D_compared_vs_reference'], 3)} & -- & NOT RUN & -- \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_numerics.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Table: E8-EXACT
    t = HEADER + "\\begin{tabular}{llrrrl}\n\\toprule\n"
    t += "Cell & Role & rejections & 1-s.\\ 95\\% lower & 1-s.\\ 95\\% upper & Verdict \\\\\n\\midrule\n"
    label_map = {"exact_sequential|target": "Exact sequential, target",
                 "corr_scale_-1|target": "Corr.\\ scale $-1$, target",
                 "exact_sequential|joint": "Exact sequential, joint",
                 "mean_shift_2.0|target": "Mean shift $2\\tau$, target",
                 "var_ratio_4.0|target": "Variance ratio 4, target",
                 "corr_scale_-1|joint": "Corr.\\ scale $-1$, joint",
                 "collapse_intermediate|target": "Collapse intermediate, target"}
    verdict_map = {"NO_EXCESS_FLAGGED": "no excess flagged", "EXCESS_FLAGGED": "excess flagged",
                   "POWERED": "powered", "NOT_POWERED": "not powered"}
    for key, blk in cells.items():
        d = blk["detector"]
        t += (f"{label_map[key]} & {blk['role']} & {d['k']}/{d['n']} & {d['cp_lower_95_one_sided']:.3f} & "
              f"{d['cp_upper_95_one_sided']:.3f} & {verdict_map[blk['verdict']]} \\\\\n")
    t += "\\midrule\n"
    nc = cells["exact_sequential|target"]
    t += (f"Always-accept rule & null / alt. & 0/{nc['detector']['n']} & -- & -- & "
          f"{verdict_map[nc['negative_controls']['always_accept']]} / "
          f"{verdict_map[cells['mean_shift_2.0|target']['negative_controls']['always_accept']]} \\\\\n")
    t += (f"Always-reject rule & null & {nc['detector']['n']}/{nc['detector']['n']} & -- & -- & "
          f"{verdict_map[nc['negative_controls']['always_reject']]} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_e8.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Appendix: predicted vs observed (all cells)
    t = HEADER + "\\begin{tabular}{llrrrrrrr}\n\\toprule\n"
    t += ("Exp. & Condition & $M$ & $D_{\\mathrm{pop}}$ & $\\mathbb{E}[d]$ & $\\bar d$ [95\\% CI] & $z$ & "
          "$\\mathbb{E}[d_J]$ & $\\bar d_J$ \\\\\n & & & \\multicolumn{6}{c}{(all $\\times10^3$)} \\\\\n\\midrule\n")
    for r in pvo:
        oj = r.get("obs_dJ")
        z = r.get("z_obs_minus_pred")
        t += (f"{r['exp'].replace('P5-', '')} & {tt(r['cond'])} & {r['m']} & "
              f"{k3(r['pop_D_target'], 3)} & {k3(r['pred_E_d'], 3)} & {ci3(r['obs_d'])} & "
              f"{'NA' if z is None else f'{z:.2f}'} & {k3(r.get('pred_E_dJ'), 3)} & "
              f"{'--' if oj is None else k3(oj['mean'])} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_reanalysis.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Appendix: z-null check
    t = HEADER + "\\begin{tabular}{llrrrrr}\n\\toprule\n"
    t += ("Exp. & Condition & skew$(d)$ & kurt$(d)$ & $t_{\\mathrm{obs}}$ & sd of $t^\\ast$ & $q_{0.95}(t^\\ast)$ \\\\\n\\midrule\n")
    for z in znull["per_condition"]:
        t += (f"{z['exp'].replace('P5-', '')} & {tt(z['cond'])} & {z['skew_d']:.2f} & "
              f"{z['kurtosis_d']:.2f} & {z['t_obs']:.2f} & {z['signflip_t_sd']:.3f} & {z['signflip_t_q95']:.3f} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_znull.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Figure data
    mc = summ["P5-E5-MC"]["conditions"]
    sz = man["data"]["nonmarkov"]["scale_from_train"]["z"]
    tau2 = man["data"]["nonmarkov"]["true"]["tau2_z_given_x"]
    eabs = 2.0 / math.sqrt(math.pi) * math.sqrt(tau2) / sz
    lines = ["M floor lo hi theory"]
    pts = [(32, mc["null_m32"]), (64, mc["null_m64"]), (128, mc["null_m128"]),
           (256, summ["P5-E1-NULL"]["conditions"]["exact_sequential"]), (512, mc["null_m512"])]
    for m, s in pts:
        fl = s["target"]["ed_floor"]
        lines.append(f"{m} {fl['mean']:.6g} {fl['lo']:.6g} {fl['hi']:.6g} {2 * eabs / m:.6g}")
    open(os.path.join(OUT, "fig_mc.dat"), "w").write("\n".join(lines) + "\n")

    joint, rows_all = rows_for(cfg, man, "nonmarkov")
    tc = sp.true_conditionals(joint)
    rows100 = rows_all[:100]

    def pop_gap(n_steps, solver, w):
        dd, de = 0.0, 0.0
        for ex in rows100:
            L = an.pfode_branch_laws(tc, ex["x"], n_steps, solver, w)
            (mb, sb), (mc_, sc_), (me, se) = L["direct"], L["sequential"], L["exact"]
            dd += an.energy_distance_gauss(mb / sz, sb / sz, mc_ / sz, sc_ / sz)
            de += an.energy_distance_gauss(me / sz, se / sz, mb / sz, sb / sz)
        return dd / len(rows100), de / len(rows100)

    lines = ["steps euler_seq euler_bias heun_seq heun_bias"]
    for st_ in (2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 96, 128, 256):
        a, b = pop_gap(st_, "euler", 0.0)
        h1, h2 = pop_gap(st_, "heun", 0.0)
        lines.append(f"{st_} {a:.6g} {b:.6g} {h1:.6g} {h2:.6g}")
    open(os.path.join(OUT, "fig_solver_closed.dat"), "w").write("\n".join(lines) + "\n")
    lines = ["w seq bias"]
    for w in (0.0, 0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0):
        a, b = pop_gap(64, "euler", w)
        lines.append(f"{w} {a:.6g} {b:.6g}")
    open(os.path.join(OUT, "fig_cfg_closed.dat"), "w").write("\n".join(lines) + "\n")
    # one-sided 5% detection resolution of mean d at the E6/E7 design (N=100, M=256)
    res = 1.6449 * max(se_e6)
    with open(os.path.join(OUT, "numbers.tex"), "a") as f:
        f.write(macro("numResolution", f"{res:.5f}"))
    lines = ["x d lo hi"]
    for w, k in ((0.5, "cfg_0.5_seq"), (1.0, "cfg_1_seq"), (2.0, "cfg_2_seq"), (4.0, "cfg_4_seq")):
        s = c("P5-E7-CFG", k)["target"]["d"]
        lines.append(f"{w} {s['mean']:.6g} {s['lo']:.6g} {s['hi']:.6g}")
    open(os.path.join(OUT, "fig_cfg_obs.dat"), "w").write("\n".join(lines) + "\n")
    print("wrote", sorted(os.listdir(OUT)))



def write_calibration_assets():
    """Contract table (pre-run closed form) and calibration results (if run)."""
    aud = load(os.path.join(ROOT, "results", "calib_contract_audit", "p5_e8_calib_v3.json"))
    aud2 = load(os.path.join(ROOT, "results", "calib_contract_audit", "p5_e8_calib_v2.json"))
    labels = {"mean_shift_0.1": "Mean shift $0.1\\tau$", "var_ratio_1.25": "Variance ratio 1.25",
              "collapse_intermediate": "Collapse, intermediate only", "corr_scale_-1": "Corr.\\ scale $-1$",
              "exact_sequential": "Exact sequential", "chain_drop_x": "Chain $z\\mid y$ (Markov)",
              "collapse_both": "Collapse, both branches"}
    order = ["exact_sequential", "chain_drop_x", "corr_scale_-1", "mean_shift_0.1", "var_ratio_1.25",
             "collapse_intermediate", "collapse_both"]
    rows = {r["cond"]: r for r in aud["contract"]}

    def yn(v):
        return "yes" if v > 1e-12 else "no"

    t = HEADER + "\\begin{tabular}{lcccrr}\n\\toprule\n"
    t += ("Condition & target law & proj.\\ joint law & truth (target) & sd ratio & $\\E\\,\\Delta$CRPS$\\times10^3$ \\\\\n"
          " & \\multicolumn{2}{c}{changed between branches?} & seq.\\ vs.\\ truth & & seq.\\ / direct \\\\\n\\midrule\n")
    for cid in order:
        r = rows[cid]
        t += (f"{labels[cid]} & {yn(r['target_D_cmp_vs_ref'])} & {yn(r['joint_proj_D_cmp_vs_ref'])} & "
              f"{yn(r['target_D_cmp_vs_truth'])} & {r['sd_ratio_cmp_z']:.3f} & "
              f"{1e3 * r['exp_crps_excess_cmp']:.2f} / {1e3 * r['exp_crps_excess_ref']:.2f} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    open(os.path.join(OUT, "tab_contract.tex"), "w").write(t)

    n = ""
    n += macro("numOCvTwo", f"{aud2['gate_oc']['P_all_null_cells_pass_if_exactly_valid']:.3f}")
    n += macro("numOCvTwoFail", f"{1 - aud2['gate_oc']['P_all_null_cells_pass_if_exactly_valid']:.2f}")
    n += macro("numOCvThree", f"{aud['gate_oc']['P_all_null_cells_pass_if_exactly_valid']:.3f}")
    n += macro("numOCvThreeGate", f"{aud['gate_oc']['P_gate_pass_if_valid_and_each_power_0.3']:.3f}")
    c2 = {c["cell"]: c for c in aud2["gate_oc"]["cells"]}
    n += macro("numOCtolFailHundred", f"{c2['corr_scale_-1|target|nonmarkov']['P_false_tolerance_fail_at_size_0.05']:.2f}")
    n += macro("numOCtolFailTwoHundred", f"{c2['exact_sequential|target|nonmarkov']['P_false_tolerance_fail_at_size_0.05']:.2f}")
    c3 = {c["cell"]: c for c in aud["gate_oc"]["cells"]}
    prim = c3["exact_sequential|target|nonmarkov"]
    n += macro("numOCprimFail", f"{1 - prim['P_cell_pass_at_size_0.05']:.3f}")
    n += macro("numOCprimDetectTen", f"{1 - prim['P_tolerance_pass_at_size_0.10']:.3f}")
    n += macro("numOCsecDetectTen", f"{c3['exact_sequential|joint|nonmarkov']['P_excess_at_size_0.10']:.2f}")
    res = aud["p_resolution"]
    n += macro("numPres", f"{res['p_min']:.3f}")
    n += macro("numPfamMax", str(res["largest_bonferroni_family_that_can_reject"]))

    cal_dir = os.path.join(ROOT, "results", "raw", "p5_e8_calib_v3")
    order_cells = ["exact_sequential|target|nonmarkov", "exact_sequential|joint|nonmarkov", "corr_scale_-1|target|nonmarkov",
                   "chain_drop_x|target|markov", "mean_shift_0.1|target|nonmarkov", "var_ratio_1.25|target|nonmarkov",
                   "collapse_intermediate|target|nonmarkov", "corr_scale_-1|joint|nonmarkov",
                   "collapse_both|target|nonmarkov", "collapse_both|joint|nonmarkov"]
    lab_cell = {k: labels[k.split("|")[0]] + (" (joint)" if "|joint|" in k else "") for k in order_cells}
    if os.path.exists(os.path.join(cal_dir, "summary.json")):
        cs = load(os.path.join(cal_dir, "summary.json"))
        cm = load(os.path.join(cal_dir, "manifest.json"))
        t = HEADER + "\\begin{tabular}{llrlll}\n\\toprule\n"
        t += ("Cell & family & rejections & 1-s.\\ 95\\% bounds & 2-s.\\ 95\\% CP & outcome \\\\\n\\midrule\n")
        for k in order_cells:
            b = cs["cells"][k]
            if b["status"] != "COMPLETED":
                t += f"{lab_cell[k]} & {b['role']} & \\multicolumn{{4}}{{l}}{{{b['status']} ({b['done']}/{b['planned']})}} \\\\\n"
                continue
            r = b["rate_95"]
            fam = {"null": "null validity", "alternative": "power", "quality_control": "quality control"}[b["role"]]
            if b["role"] == "null":
                crit = "Bonferroni excess" + (", tolerance" if "tolerance_pass" in b else "")
                ok = (not b["excess_flag"]) and b.get("tolerance_pass", True)
                out = ("within tolerance, " if "tolerance_pass" in b and b["tolerance_pass"] else ("tolerance FAILED, " if "tolerance_pass" in b else "")) + ("excess flagged" if b["excess_flag"] else "no excess")
            elif b["role"] == "alternative":
                crit = "powered"
                out = "POWERED" if b["powered"] else "NOT POWERED"
            else:
                crit = "not rejected; quality flagged"
                out = ("not rejected" if not b["compat_test_rejects_any"] else "REJECTED") + "; " + (
                    "quality flagged" if b["quality_flag_all_reps"] else "quality NOT flagged")
            two = st.clopper_pearson(r["k"], r["n"], 0.95, "two")
            t += (f"{lab_cell[k]} & {fam} & {r['k']}/{r['n']} & {r['cp_lower']:.3f}, {r['cp_upper']:.3f} & "
                  f"[{two['lo']:.3f}, {two['hi']:.3f}] & {out} \\\\\n")
        t += "\\bottomrule\n\\end{tabular}\n"
        open(os.path.join(OUT, "tab_calib.tex"), "w").write(t)
        t = HEADER + "\\begin{tabular}{lrrrr}\n\\toprule\n"
        t += ("Cell & $\\overline{\\Delta\\mathrm{CRPS}}$ seq.\\ & $\\overline{\\Delta\\mathrm{CRPS}}$ direct & sd ratio seq.\\ & reps with CI $>0$ \\\\\n\\midrule\n")
        for k in order_cells:
            b = cs["cells"][k]
            if b["status"] != "COMPLETED":
                continue
            t += (f"{lab_cell[k]} & {1e3 * b['mean_excess_crps_seq']:.2f} & {1e3 * b['mean_excess_crps_direct']:.2f} & "
                  f"{b['mean_sd_ratio_seq']:.3f} & {100 * b['frac_reps_excess_crps_seq_ci_above_0']:.0f}\\% \\\\\n")
        t += "\\bottomrule\n\\end{tabular}\n"
        open(os.path.join(OUT, "tab_calib_quality.tex"), "w").write(t)
        g = cs["gate"]
        n += macro("numCalibGate", "PASS" if g["gate_pass"] else ("FAIL" if g["gate_pass"] is False else "INCOMPLETE"))
        for key, name in (("G1_primary_tolerance", "numCalibGOne"), ("G2_null_family_no_excess", "numCalibGTwo"), ("G3_power_family", "numCalibGThree")):
            n += macro(name, ("pass" if g.get(key) else "fail") if key in g else "n/a")
        pr = cs["cells"]["exact_sequential|target|nonmarkov"]["rate_95"]
        n += macro("numCalibPrimK", f"{pr['k']}/{pr['n']}")
        n += macro("numCalibPrimLo", f"{pr['cp_lower']:.3f}")
        n += macro("numCalibPrimHi", f"{pr['cp_upper']:.3f}")
        two = st.clopper_pearson(pr["k"], pr["n"], 0.95, "two")
        n += macro("numCalibPrimTwoLo", f"{two['lo']:.3f}")
        n += macro("numCalibPrimTwoHi", f"{two['hi']:.3f}")
        n += macro("numCalibWall", f"{cm['wall_seconds'] / 60:.1f}")
        n += macro("numCalibCPU", f"{cm['cpu_seconds_tasks'] / 60:.1f}")
        for k, name in (("mean_shift_0.1|target|nonmarkov", "Shift"), ("var_ratio_1.25|target|nonmarkov", "Var"),
                        ("collapse_intermediate|target|nonmarkov", "CollInt"), ("corr_scale_-1|joint|nonmarkov", "CorrJ")):
            b = cs["cells"][k]
            n += macro("numCalibPow" + name, f"{b['rate_95']['k']}/{b['rate_95']['n']}" if b["status"] == "COMPLETED" else "NOT RUN")
        for k, name in (("exact_sequential|joint|nonmarkov", "NullJ"), ("corr_scale_-1|target|nonmarkov", "NullCorrT"),
                        ("chain_drop_x|target|markov", "NullChain")):
            b = cs["cells"][k]
            n += macro("numCalib" + name, f"{b['rate_95']['k']}/{b['rate_95']['n']}" if b["status"] == "COMPLETED" else "NOT RUN")
    else:
        n += macro("numCalibGate", "NOT RUN")
    with open(os.path.join(OUT, "numbers.tex"), "a") as f:
        f.write(n)


def write_synlearn_assets():
    """Table and macros for P5-SYN-LEARN-01 (coherent-joint controls)."""
    path = os.path.join(ROOT, "results", "raw", "p5_syn_learn_01_test", "summary.json")
    n = ""
    if not os.path.exists(path):
        n += macro("numSynStatus", "NOT RUN")
        with open(os.path.join(OUT, "numbers.tex"), "a") as f:
            f.write(n)
        return
    s = load(path)
    man = load(os.path.join(ROOT, "results", "raw", "p5_syn_learn_01_test", "manifest.json"))
    lab = {"TRUE_JOINT_CONTROL": "True joint (exact mixture)", "FITTED_JOINT_CONTROL": "Fitted joint (EM, $K=2$)",
           "INDEPENDENT_CONDITIONAL_FM": "Independent conditional FM", "SHARED_CONDITIONAL_FM": "Shared conditional FM"}
    ll = {"TRUE_JOINT_CONTROL": s["heldout_loglik"]["true_mean_loglik"], "FITTED_JOINT_CONTROL": s["heldout_loglik"]["fitted_mean_loglik"]}
    t = HEADER + "\\begin{tabular}{lrrrrr}\n\\toprule\n"
    t += ("Model & $p_T$ & $p_J$ & $\\widehat{\\Delta}_T\\times10^3$ [95\\% CI] & $D(\\text{model},\\text{truth})\\times10^3$ [95\\% CI] & test log-lik. \\\\\n\\midrule\n")
    fm_exists = os.path.exists(os.path.join(ROOT, "results", "raw", "p5_syn_learn_01_fm_test", "summary.json"))
    for name in ("TRUE_JOINT_CONTROL", "FITTED_JOINT_CONTROL", "INDEPENDENT_CONDITIONAL_FM", "SHARED_CONDITIONAL_FM"):
        r = s["results"][name]
        if r.get("status") == "NOT_RUN":
            # The round-4 controls file records the flow arms as NOT_RUN; they ran in round 6 (tab:fm).
            if fm_exists and name == "INDEPENDENT_CONDITIONAL_FM":
                t += "Neural flow arms (round 6) & \\multicolumn{5}{l}{see \\cref{tab:fm}} \\\\\n"
            elif not fm_exists:
                t += f"{lab[name]} & \\multicolumn{{5}}{{l}}{{NOT RUN (no tensor library; installation not approved)}} \\\\\n"
            continue
        tg, jt = r["target"], r["joint"]
        e, q = tg["effect_ED_U"], tg["quality_ED_to_truth"]
        t += (f"{lab[name]} & {tg['p']:.3f} & {jt['p']:.3f} & {1e3 * e['mean']:.2f} [{1e3 * e['lo']:.2f}, {1e3 * e['hi']:.2f}] & "
              f"{1e3 * q['mean']:.2f} [{1e3 * q['lo']:.2f}, {1e3 * q['hi']:.2f}] & {ll[name]:.3f} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    open(os.path.join(OUT, "tab_synlearn.tex"), "w").write(t)
    R = s["results"]
    n += macro("numSynStatus", "RUN")
    n += macro("numSynTrueP", f"{R['TRUE_JOINT_CONTROL']['target']['p']:.3f}")
    n += macro("numSynTruePJ", f"{R['TRUE_JOINT_CONTROL']['joint']['p']:.3f}")
    n += macro("numSynFitP", f"{R['FITTED_JOINT_CONTROL']['target']['p']:.3f}")
    n += macro("numSynFitPJ", f"{R['FITTED_JOINT_CONTROL']['joint']['p']:.3f}")
    n += macro("numSynHolmTrue", f"{s['primary_family']['holm_p']['TRUE_JOINT_CONTROL']:.2f}")
    n += macro("numSynHolmFit", f"{s['primary_family']['holm_p']['FITTED_JOINT_CONTROL']:.2f}")
    q = R["FITTED_JOINT_CONTROL"]["target"]["quality_ED_to_truth"]
    n += macro("numSynFitQ", f"{q['mean']:.3f} [{q['lo']:.3f}, {q['hi']:.3f}]")
    qj = R["FITTED_JOINT_CONTROL"]["joint"]["quality_projected_ED_to_truth"]
    n += macro("numSynFitQJ", f"{qj['mean']:.3f} [{qj['lo']:.3f}, {qj['hi']:.3f}]")
    e = R["TRUE_JOINT_CONTROL"]["joint"]["effect_ED_U"]
    n += macro("numSynTrueEJ", f"{1e3 * e['mean']:.2f} [{1e3 * e['lo']:.2f}, {1e3 * e['hi']:.2f}]")
    n += macro("numSynFitSdr", f"{R['FITTED_JOINT_CONTROL']['target']['sd_ratio_direct']['mean']:.3f}")
    n += macro("numSynLLTrue", f"{ll['TRUE_JOINT_CONTROL']:.3f}")
    n += macro("numSynLLFit", f"{ll['FITTED_JOINT_CONTROL']:.3f}")
    n += macro("numSynWall", f"{man['wall_seconds']:.1f}")
    n += macro("numSynEMIter", str(s["fitted_model"]["em"]["iterations"]))
    with open(os.path.join(OUT, "numbers.tex"), "a") as f:
        f.write(n)


def write_fm_assets():
    """Tables and macros for the P5-SYN-LEARN-01 flow-matching arms (round 6)."""
    base = os.path.join(ROOT, "results", "raw")
    tdir, ddir, trdir = (os.path.join(base, f"p5_syn_learn_01_fm_{k}") for k in ("test", "dev", "train"))
    n = ""
    if not os.path.exists(os.path.join(tdir, "summary.json")):
        n += macro("numFmStatus", "NOT RUN")
        with open(os.path.join(OUT, "numbers.tex"), "a") as f:
            f.write(n)
        return
    s, d, tr = load(os.path.join(tdir, "summary.json")), load(os.path.join(ddir, "summary.json")), load(os.path.join(trdir, "training.json"))
    man, labels = load(os.path.join(trdir, "manifest.json")), load(os.path.join(ddir, "labels.json"))
    arms = [("INDEPENDENT_CONDITIONAL_FM", "Ind", "Independent conditional FM"), ("SHARED_CONDITIONAL_FM", "Sh", "Shared conditional net")]
    prim, sec = 128, 32

    def ci3(c):
        return f"{1e3 * c['mean']:.2f} [{1e3 * c['lo']:.2f}, {1e3 * c['hi']:.2f}]"

    def ci2(c):
        return f"{c['mean']:.3f} [{c['lo']:.3f}, {c['hi']:.3f}]"

    # Main results table (test split; both solver levels).
    t = HEADER + "\\begin{tabular}{llrrrrr}\n\\toprule\n"
    t += ("Arm & steps & $p_T$ & $p_J^U$ & $\\widehat{\\Delta}_T\\times10^3$ [95\\% CI] & $\\widehat{\\Delta}_J^U\\times10^3$ [95\\% CI] & $\\widehat{D}_U(\\text{direct},\\text{truth})\\times10^3$ [95\\% CI] \\\\\n\\midrule\n")
    for arm, short, lab in arms:
        for steps in (prim, sec):
            bt, bj = s["blocks"][f"{arm}|target|{steps}"], s["blocks"][f"{arm}|joint|{steps}"]
            t += (f"{lab} & {steps}{' (primary)' if steps == prim else ''} & {bt['p']:.3f} & {bj['p']:.3f} & {ci3(bt['effect_ED_U'])} & "
                  f"{ci3(bj['effect_ED_U'])} & {ci3(bt['quality_direct_ED_U_to_truth'])} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    open(os.path.join(OUT, "tab_fm.tex"), "w").write(t)
    # Cost and diagnostics table.
    t = HEADER + "\\begin{tabular}{lrrrrrr}\n\\toprule\n"
    t += "Arm & params & updates & train CPU-s & sampling CPU-s (test) & dev-loss decrease 90$\\to$100\\% (max) & solver paired $\\times10^3$ [95\\% CI] \\\\\n\\midrule\n"
    for arm, short, lab in arms:
        ti = tr[arm]
        samp = sum(b["timing_sampling"]["cpu_seconds"] for k, b in s["blocks"].items() if k.startswith(arm + "|"))
        rel = max(ti["dev_loss_rel_decrease_90_to_100"].values())
        sol = s["solver_sensitivity"][f"{arm}|target"]["paired_ED_U_fine_minus_coarse"]
        t += (f"{lab} & {ti['n_params']['total']} & {ti['updates']} & {ti['train_cpu_seconds']:.0f} & {samp:.0f} & "
              f"{100 * rel:.2f}\\% & {ci3(sol)} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    open(os.path.join(OUT, "tab_fm_cost.tex"), "w").write(t)
    n += macro("numFmStatus", man["status"])
    for arm, short, lab in arms:
        bt, bj = s["blocks"][f"{arm}|target|{prim}"], s["blocks"][f"{arm}|joint|{prim}"]
        b32 = s["blocks"][f"{arm}|target|{sec}"]
        n += macro(f"numFm{short}P", f"{bt['p']:.3f}")
        n += macro(f"numFm{short}PJ", f"{bj['p']:.3f}")
        n += macro(f"numFm{short}PThirtyTwo", f"{b32['p']:.3f}")
        n += macro(f"numFm{short}Holm", f"{s['primary_family']['holm_p'][arm]:.3f}")
        n += macro(f"numFm{short}D", ci3(bt["effect_ED_U"]))
        n += macro(f"numFm{short}DJ", ci3(bj["effect_ED_U"]))
        n += macro(f"numFm{short}Q", ci3(bt["quality_direct_ED_U_to_truth"]))
        n += macro(f"numFm{short}QSeq", ci3(bt["quality_seq_ED_U_to_truth"]))
        n += macro(f"numFm{short}QJ", ci3(bj["quality_direct_projected_ED_U_to_truth"]))
        n += macro(f"numFm{short}Sdr", ci2(bt["sd_ratio_direct"]))
        n += macro(f"numFm{short}Shift", ci2(bt["mean_shift_direct_std"]))
        n += macro(f"numFm{short}MinDistinct", str(bt["min_distinct_intermediates"]))
        sol = s["solver_sensitivity"][f"{arm}|target"]
        n += macro(f"numFm{short}Solver", ci3(sol["paired_ED_U_fine_minus_coarse"]))
        n += macro(f"numFm{short}SolverFlag", "yes" if sol["SOLVER_SENSITIVE"] else "no")
        solj = s["solver_sensitivity"][f"{arm}|joint"]
        n += macro(f"numFm{short}SolverJ", ci3(solj["paired_ED_U_fine_minus_coarse"]))
        n += macro(f"numFm{short}SolverQ", ci3(sol["paired_quality_fine_minus_coarse"]))
        ti = tr[arm]
        n += macro(f"numFm{short}Params", str(ti["n_params"]["total"]))
        n += macro(f"numFm{short}Updates", str(ti["updates"]))
        n += macro(f"numFm{short}TrainCPU", f"{ti['train_cpu_seconds']:.0f}")
        n += macro(f"numFm{short}TrainWall", f"{ti['train_wall_seconds']:.0f}")
        n += macro(f"numFm{short}Under", f"{100 * max(ti['dev_loss_rel_decrease_90_to_100'].values()):.2f}")
        n += macro(f"numFm{short}UnderFlag", "yes" if ti.get("UNDERTRAINING_FLAG") else "no")
        n += macro(f"numFm{short}Label", labels[arm]["label"].replace("_", "\\_"))
        n += macro(f"numFm{short}DevP", f"{d['blocks'][f'{arm}|target|{prim}']['p']:.3f}")
        samp = sum(b["timing_sampling"]["cpu_seconds"] for k, b in s["blocks"].items() if k.startswith(arm + "|"))
        n += macro(f"numFm{short}SampCPU", f"{samp:.0f}")
        n += macro(f"numFm{short}Exposure", ", ".join(f"{k}: {v}" for k, v in ti["pattern_exposure"].items()).replace("|", "$\\mid$"))
    bw = s["between_arms"][f"target|{prim}"]
    n += macro("numFmBetween", ci3(bw["paired_normal"]))
    n += macro("numFmBetweenBoot", f"[{1e3 * bw['bootstrap']['lo']:.2f}, {1e3 * bw['bootstrap']['hi']:.2f}]")
    n += macro("numFmBetweenN", str(bw["paired_normal"]["n_pairs"]))
    bwj = s["between_arms"][f"joint|{prim}"]
    n += macro("numFmBetweenJ", ci3(bwj["paired_normal"]))
    bw32 = s["between_arms"][f"target|{sec}"]
    n += macro("numFmBetweenThirtyTwo", ci3(bw32["paired_normal"]))
    n += macro("numFmCPU", f"{man['budget']['cpu_seconds_this_process']:.0f}")
    n += macro("numFmBudgetCPU", f"{man['budget']['cpu_seconds_total_incl_before']:.0f}")
    n += macro("numFmWall", f"{man['budget']['wall_seconds']:.0f}")
    n += macro("numFmTorch", man["torch"].replace("+", "{+}"))
    with open(os.path.join(OUT, "numbers.tex"), "a") as f:
        f.write(n)


def write_reference_lines():
    """Horizontal reference line data (detection resolution) for the figure."""
    num = open(os.path.join(OUT, "numbers.tex")).read()
    res = float(num.split("\\numResolution}{")[1].split("}")[0])
    open(os.path.join(OUT, "fig_res_steps.dat"), "w").write(f"x y\n2 {res}\n256 {res}\n")
    open(os.path.join(OUT, "fig_res_w.dat"), "w").write(f"x y\n0 {res}\n4 {res}\n")


if __name__ == "__main__":
    main()
    write_reference_lines()
    write_calibration_assets()
    write_synlearn_assets()
    write_fm_assets()
