"""Render results/raw/<run_id>/summary.json as Markdown tables.

Usage: python3 scripts/make_tables.py results/raw/p5_first_run_v1_test > results/p5_first_run_v1_test_tables.md
"""

import json
import os
import sys


def f(v, nd=4):
    if v is None:
        return "NA"
    if isinstance(v, bool):
        return str(v)
    return f"{v:.{nd}f}"


def ci(blk, nd=4):
    if blk is None or blk.get("mean") is None:
        return "NA"
    if blk.get("lo") is None:
        return f(blk["mean"], nd)
    return f"{f(blk['mean'], nd)} [{f(blk['lo'], nd)}, {f(blk['hi'], nd)}]"


def cond_table(exp_id, exp):
    out = [f"### {exp_id} (joint = {exp['joint']})", ""]
    if "error" in exp:
        out += [f"**FAIL**: {exp['error']}", ""]
    out.append("| condition | M | N | ED floor (A,B) | ED (A,C) | d = ED(A,C)-ED(A,B) [95% CI] | p (target) | target | "
               "joint dJ [95% CI] | p (joint) | joint | expectation |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for cid, s in exp["conditions"].items():
        if s.get("status") == "NOT_RUN":
            out.append(f"| {cid} | | | NOT_RUN | | | | | | | | |")
            continue
        t, j = s["target"], s["joint"]
        tdet = "DETECTED" if t["detected"] else "not detected"
        jdet = "NA" if j is None else ("DETECTED" if j["detected"] else "not detected")
        exp_s = ", ".join(f"{k}:{v}" for k, v in s["expectation"].items())
        out.append(
            f"| {cid} | {s['m']} | {s['n_examples']} | {f(t['ed_floor']['mean'])} | {f(t['ed_cmp']['mean'])} | {ci(t['d'])} | "
            f"{f(t['p_sign_flip'], 3)} | {tdet} | {'NA' if j is None else ci(j['dJ'])} | "
            f"{'NA' if j is None else f(j['p_sign_flip'], 3)} | {jdet} | {exp_s} |")
    out += ["", "Quality / proper-score / diagnostic columns (means over examples, 95% CI; oracle = uses true conditional):", ""]
    out.append("| condition | CRPS ref | CRPS cmp | CRPS cmp-ref [95% CI] | fidelity ref (oracle) | fidelity cmp (oracle) | "
               "diversity ref sd/tau (oracle) | diversity cmp sd/tau (oracle) | bias ref /tau (oracle) | bias cmp /tau (oracle) | "
               "mean diff /tau | log sd ratio (n undefined) | paired-index MSE /tau^2 (invalid metric) |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for cid, s in exp["conditions"].items():
        if s.get("status") == "NOT_RUN":
            continue
        out.append(
            f"| {cid} | {f(s['crps_ref']['mean'])} | {f(s['crps_cmp']['mean'])} | {ci(s['crps_diff_cmp_minus_ref'])} | "
            f"{f(s['fid_ref']['mean'], 3)} | {f(s['fid_cmp']['mean'], 3)} | {f(s['div_ref']['mean'], 3)} | {f(s['div_cmp']['mean'], 3)} | "
            f"{f(s['bias_ref_over_tau']['mean'], 3)} | {f(s['bias_cmp_over_tau']['mean'], 3)} | {ci(s['mean_diff_over_tau'], 3)} | "
            f"{ci(s['log_sd_ratio'], 3)} ({s['n_log_sd_ratio_undefined']}) | {f(s['paired_mse_over_tau2']['mean'], 3)} |")
    out.append("")
    return out


def reps_table(exp_id, exp):
    out = [f"### {exp_id} (joint = {exp['joint']})", ""]
    if "error" in exp:
        out += [f"**FAIL**: {exp['error']}", ""]
        return out
    ft, fj = exp["fpr_target"], exp["fpr_joint"]
    out.append("| level | rejections / replicates | FPR | Wilson 95% CI | mean z over reps | sd z over reps |")
    out.append("|---|---|---|---|---|---|")
    zt, zj = exp["z_target_mean_sd"], exp["z_joint_mean_sd"]
    out.append(f"| target | {ft['k']}/{ft['n']} | {f(ft['rate'], 3)} | [{f(ft['lo'], 3)}, {f(ft['hi'], 3)}] | {f(zt['mean'], 3)} | {f(zt['sd'], 3)} |")
    out.append(f"| joint | {fj['k']}/{fj['n']} | {f(fj['rate'], 3)} | [{f(fj['lo'], 3)}, {f(fj['hi'], 3)}] | {f(zj['mean'], 3)} | {f(zj['sd'], 3)} |")
    out.append("")
    return out


def main():
    run_dir = sys.argv[1]
    with open(os.path.join(run_dir, "summary.json")) as fh:
        summ = json.load(fh)
    with open(os.path.join(run_dir, "manifest.json")) as fh:
        man = json.load(fh)
    lines = [f"# Tables for run `{man['run_id']}` (split = {man['split']})", "",
             f"Generated by scripts/make_tables.py from `{os.path.relpath(run_dir)}/summary.json`. "
             f"Total runtime {man['total_seconds']:.1f}s (budget {man['budget_seconds']}s). "
             "ED values are on train-split-standardised scale.", ""]
    lines.append("| experiment | status | seconds |")
    lines.append("|---|---|---|")
    for eid, e in man["experiments"].items():
        lines.append(f"| {eid} | {e['status']} | {e.get('seconds', 0):.1f} |")
    lines.append("")
    for eid, exp in summ.items():
        if "replicates" in exp or "fpr_target" in exp:
            lines += reps_table(eid, exp)
        else:
            lines += cond_table(eid, exp)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
