"""Generate LaTeX tables, pgfplots data and numeric macros for paper/main.tex
from committed raw results. No sampling is performed; closed-form curves are
computed with p5compat.analytic on the regenerated (digest-checked) v1 rows.

Usage: python3 scripts/make_paper_assets.py
Outputs: paper/generated/*.tex, paper/generated/*.dat
"""

import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from p5compat import analytic as an  # noqa: E402
from p5compat import samplers as sp  # noqa: E402
from p5compat import stats as st  # noqa: E402
from reanalyse_v1 import rows_for  # noqa: E402

OUT = os.path.join(ROOT, "paper", "generated")
V1 = os.path.join(ROOT, "results", "raw", "p5_first_run_v1_test")
E8 = os.path.join(ROOT, "results", "raw", "p5_e8_exact_v1")
RE = os.path.join(ROOT, "results", "reanalysis_v1")

HEADER = "% AUTO-GENERATED by scripts/make_paper_assets.py from committed raw results. Do not edit by hand.\n"


def load(p):
    with open(p) as f:
        return json.load(f)


def k3(v, nd=2):
    """value x 1e3 formatted."""
    return "--" if v is None else f"{1e3 * v:.{nd}f}"


def ci3(b, nd=2):
    if b is None or b.get("mean") is None:
        return "--"
    return f"{k3(b['mean'], nd)} [{k3(b['lo'], nd)}, {k3(b['hi'], nd)}]"


def pv(p):
    return "--" if p is None else f"{p:.3f}"


def tt(name):
    return "\\texttt{" + name.replace("_", "\\_") + "}"


def macro(name, value):
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def main():
    os.makedirs(OUT, exist_ok=True)
    cfg = load(os.path.join(ROOT, "configs", "p5_first_run.json"))
    man = load(os.path.join(V1, "manifest.json"))
    summ = load(os.path.join(V1, "summary.json"))
    pvo = load(os.path.join(RE, "predicted_vs_observed.json"))
    gaps = load(os.path.join(RE, "population_gaps.json"))
    znull = load(os.path.join(RE, "z_null_check.json"))
    e8 = load(os.path.join(E8, "summary.json"))
    e8man = load(os.path.join(E8, "manifest.json"))
    pred = {(r["exp"], r["cond"]): r for r in pvo}

    def c(eid, cid):
        return summ[eid]["conditions"][cid]

    # ------------------------------------------------------------------ numbers
    n = HEADER
    e1 = c("P5-E1-NULL", "exact_sequential")
    n += macro("numNullP", pv(e1["target"]["p_sign_flip"]))
    n += macro("numNullPjoint", pv(e1["joint"]["p_sign_flip"]))
    n += macro("numMarkovNullP", pv(c("P5-E4-MARKOV", "exact_sequential")["target"]["p_sign_flip"]))
    reps = summ["P5-E1-NULL-REPS"]
    n += macro("numRepRejT", f"{reps['fpr_target']['k']}/{reps['fpr_target']['n']}")
    n += macro("numRepRejJ", f"{reps['fpr_joint']['k']}/{reps['fpr_joint']['n']}")
    rb = znull["replicates"]
    n += macro("numRepCPlo", f"{rb['cp_two_sided_target']['lo']:.3f}")
    n += macro("numRepCPhi", f"{rb['cp_two_sided_target']['hi']:.3f}")
    n += macro("numRepZsd", f"{rb['sd_z_target']:.2f}")
    n += macro("numRepZsdLo", f"{rb['sd_ci_target'][0]:.2f}")
    n += macro("numRepZsdHi", f"{rb['sd_ci_target'][1]:.2f}")
    sdt = [z["signflip_t_sd"] for z in znull["per_condition"]]
    q95 = [z["signflip_t_q95"] for z in znull["per_condition"]]
    ku = [z["kurtosis_d"] for z in znull["per_condition"]]
    n += macro("numZflipSdMin", f"{min(sdt):.3f}")
    n += macro("numZflipSdMax", f"{max(sdt):.3f}")
    n += macro("numZflipQmin", f"{min(q95):.2f}")
    n += macro("numZflipQmax", f"{max(q95):.2f}")
    n += macro("numKurtMin", f"{min(ku):.1f}")
    n += macro("numKurtMax", f"{max(ku):.1f}")
    n += macro("numFloorM", f"{e1['target']['ed_floor']['mean']:.4f}")
    cb = c("P5-E3-COLLAPSE", "collapse_both")
    crps_exact = e1["crps_ref"]["mean"]
    crps_coll = cb["crps_ref"]["mean"]
    n += macro("numCRPSexact", f"{crps_exact:.3f}")
    n += macro("numCRPScollapse", f"{crps_coll:.3f}")
    n += macro("numCRPScollapsePct", f"{100 * (crps_coll / crps_exact - 1):.1f}")
    n += macro("numCRPScollapseTheoryPct", f"{100 * (math.sqrt(2) - 1):.1f}")
    ci = c("P5-E3-COLLAPSE", "collapse_intermediate")
    n += macro("numCollIntD", f"{ci['target']['d']['mean']:.4f}")
    n += macro("numCollIntDiv", f"{ci['div_cmp']['mean']:.2f}")
    n += macro("numCollIntMSE", f"{ci['paired_mse_over_tau2']['mean']:.2f}")
    n += macro("numExactMSE", f"{e1['paired_mse_over_tau2']['mean']:.2f}")
    oi = c("P5-E4-INTERMEDIATE", "observed_intermediate")
    ob = oi["crps_diff_cmp_minus_ref"]
    n += macro("numObsIntCRPS", f"{ob['mean']:.3f} [{ob['lo']:.3f}, {ob['hi']:.3f}]")
    corr_p = [c("P5-E2-CHECKER", f"corr_scale_{s}")["target"]["p_sign_flip"] for s in ("-1", "0", "0.5")]
    n += macro("numCorrPmin", pv(min(corr_p)))
    n += macro("numCorrPmax", pv(max(corr_p)))
    zt = [abs(r["z_obs_minus_pred"]) for r in pvo if r.get("z_obs_minus_pred") is not None]
    zj = [abs(r["zJ_obs_minus_pred"]) for r in pvo if r.get("zJ_obs_minus_pred") is not None]
    n += macro("numPredCellsT", str(len(zt)))
    n += macro("numPredCellsJ", str(len(zj)))
    n += macro("numPredZmaxT", f"{max(zt):.2f}")
    n += macro("numPredZmaxJ", f"{max(zj):.2f}")
    g = {x["cond"]: x for x in gaps}
    n += macro("numGapPrior", f"{g['exact_flow_limit']['pop_D_compared_vs_reference']:.5f}")
    for w, key in (("0.5", "cfg_0.5_seq"), ("1", "cfg_1_seq"), ("2", "cfg_2_seq"), ("4", "cfg_4_seq")):
        n += macro("numGapCFG" + {"0.5": "Half", "1": "One", "2": "Two", "4": "Four"}[w],
                   f"{g[key]['pop_D_compared_vs_reference']:.3f}")
    n += macro("numGapEulerSixtyFour", f"{g['euler_64_seq']['pop_D_compared_vs_reference']:.5f}")
    n += macro("numGapEulerFour", f"{g['euler_4_seq']['pop_D_compared_vs_reference']:.5f}")
    n += macro("numBiasEulerSixteen", f"{g['euler_16_direct_vs_exact']['pop_D_compared_vs_reference']:.4f}")
    n += macro("numBiasCFGFour", f"{g['cfg_4_direct_vs_exact']['pop_D_compared_vs_reference']:.3f}")
    n += macro("numBiasCFGOne", f"{g['cfg_1_direct_vs_exact']['pop_D_compared_vs_reference']:.4f}")
    se_e6 = [c("P5-E6-SOLVER", k)["target"]["d"]["se"] for k in ("euler_8_seq", "euler_16_seq", "euler_32_seq", "euler_64_seq")]
    n += macro("numSEsolverMin", f"{min(se_e6):.4f}")
    n += macro("numSEsolverMax", f"{max(se_e6):.4f}")
    n += macro("numRuntimeVone", f"{man['total_seconds']:.1f}")
    n += macro("numRuntimeEeight", f"{e8man['total_seconds']:.1f}")
    cells = e8["C"]["cells"]
    nul = cells["exact_sequential|target"]["detector"]
    n += macro("numEeightNullK", f"{nul['k']}/{nul['n']}")
    n += macro("numEeightNullLo", f"{nul['cp_lower_95_one_sided']:.3f}")
    n += macro("numEeightNullHi", f"{nul['cp_upper_95_one_sided']:.3f}")
    ms = cells["mean_shift_2.0|target"]["detector"]
    n += macro("numEeightShiftK", f"{ms['k']}/{ms['n']}")
    n += macro("numEeightShiftLo", f"{ms['cp_lower_95_one_sided']:.3f}")
    n += macro("numEeightAdatasets", str(e8["A"]["n_datasets"]))
    n += macro("numEeightBdatasets", str(e8["B"]["n_datasets"]))
    n += macro("numEeightBminP", f"{e8['B']['min_p_mc']:.4f}")
    calib = load(os.path.join(ROOT, "configs", "p5_e8_calib_v2.json"))
    n += macro("numCalibCPUmin", f"{calib['resource_estimate']['estimated_cpu_minutes']:.0f}")
    with open(os.path.join(OUT, "numbers.tex"), "w") as f:
        f.write(n)

    # ------------------------------------------------------------------ re-aggregation from raw
    def raw_rows(eid, cid):
        with open(os.path.join(V1, f"{eid}.jsonl")) as fh:
            return {r["i"]: r for r in map(json.loads, fh) if r["cond"] == cid}

    ex_rows = raw_rows("P5-E1-NULL", "exact_sequential")
    cb_rows = raw_rows("P5-E3-COLLAPSE", "collapse_both")
    collapse_vs_exact = st.mean_ci([cb_rows[i]["crps_cmp"] - ex_rows[i]["crps_ref"] for i in sorted(ex_rows)])
    n_extra = macro("numCollapseVsExactCRPS", f"{collapse_vs_exact['mean']:.3f} [{collapse_vs_exact['lo']:.3f}, {collapse_vs_exact['hi']:.3f}]")
    with open(os.path.join(OUT, "numbers.tex"), "a") as f:
        f.write(n_extra)

    # ------------------------------------------------------------------ Table: controls
    rows = [
        ("P5-E1-NULL", "exact_sequential", "Exact sequential (null)"),
        ("P5-E2-CHECKER", "mean_shift_0.05", "Mean shift $0.05\\tau$"),
        ("P5-E2-CHECKER", "mean_shift_0.1", "Mean shift $0.1\\tau$"),
        ("P5-E2-CHECKER", "mean_shift_0.5", "Mean shift $0.5\\tau$"),
        ("P5-E2-CHECKER", "var_ratio_0.8", "Variance ratio 0.8"),
        ("P5-E2-CHECKER", "var_ratio_1.1", "Variance ratio 1.1"),
        ("P5-E2-CHECKER", "var_ratio_1.5", "Variance ratio 1.5"),
        ("P5-E2-CHECKER", "corr_scale_-1", "Corr.\\ scale $-1$ (target exact)"),
        ("P5-E2-CHECKER", "corr_scale_0.5", "Corr.\\ scale $0.5$ (target exact)"),
        ("P5-E3-COLLAPSE", "collapse_both", "Collapse, both branches"),
        ("P5-E3-COLLAPSE", "collapse_intermediate", "Collapse, intermediate only"),
        ("P5-E4-INTERMEDIATE", "observed_intermediate", "Observed intermediate"),
        ("P5-E4-INTERMEDIATE", "chain_drop_x", "Chain $z\\mid y$ (non-Markov)"),
        ("P5-E4-MARKOV", "chain_drop_x", "Chain $z\\mid y$ (Markov)"),
    ]
    t = HEADER + "\\begin{tabular}{lrrrrrr}\n\\toprule\n"
    t += ("Condition & $\\bar d\\times10^3$ [95\\% CI] & $p_T$ & $\\bar d_J\\times10^3$ & $p_J$ & "
          "$\\Delta\\mathrm{CRPS}\\times10^3$ [95\\% CI] & sd ratio \\\\\n\\midrule\n")
    for eid, cid, label in rows:
        s = c(eid, cid)
        j = s["joint"]
        crps_cell = ci3(s["crps_diff_cmp_minus_ref"], 1)
        if cid == "collapse_both":
            # re-aggregated from raw: paired by example against the exact direct sampler (same rows)
            crps_cell = ci3(collapse_vs_exact, 1) + "$^\\dagger$"
        t += (f"{label} & {ci3(s['target']['d'])} & {pv(s['target']['p_sign_flip'])} & "
              f"{'--' if j is None else k3(j['dJ']['mean'])} & {'--' if j is None else pv(j['p_sign_flip'])} & "
              f"{crps_cell} & {s['div_cmp']['mean']:.2f} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_controls.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Table: numerical components
    nrows = [
        ("P5-E6-SOLVER", "euler_2_seq", "Euler, 2 steps"),
        ("P5-E6-SOLVER", "euler_4_seq", "Euler, 4 steps"),
        ("P5-E6-SOLVER", "euler_8_seq", "Euler, 8 steps"),
        ("P5-E6-SOLVER", "euler_64_seq", "Euler, 64 steps"),
        ("P5-E6-SOLVER", "heun_4_seq", "Heun, 4 steps"),
        ("P5-E6-SOLVER", "heun_16_seq", "Heun, 16 steps"),
        ("P5-E7-CFG", "cfg_0.5_seq", "Euler 64, $w=0.5$"),
        ("P5-E7-CFG", "cfg_1_seq", "Euler 64, $w=1$"),
        ("P5-E7-CFG", "cfg_4_seq", "Euler 64, $w=4$"),
    ]
    t = HEADER + "\\begin{tabular}{lrrrr}\n\\toprule\n"
    t += ("Sampler (both branches) & $D_{\\mathrm{pop}}\\times10^3$ & $\\mathbb{E}[d]\\times10^3$ & "
          "$\\bar d\\times10^3$ [95\\% CI] & $p_T$ \\\\\n\\midrule\n")
    for eid, cid, label in nrows:
        s = c(eid, cid)
        r = pred[(eid, cid)]
        t += (f"{label} & {k3(r['pop_D_target'], 3)} & {k3(r['pred_E_d'], 3)} & {ci3(s['target']['d'])} & "
              f"{pv(s['target']['p_sign_flip'])} \\\\\n")
    gl = g["exact_flow_limit"]
    t += (f"Exact flow, $N\\to\\infty$ & {k3(gl['pop_D_compared_vs_reference'], 3)} & -- & NOT RUN & -- \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_numerics.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Table: E8-EXACT
    t = HEADER + "\\begin{tabular}{llrrrl}\n\\toprule\n"
    t += "Cell & Role & rejections & CP$_{95}$ lower & CP$_{95}$ upper & Verdict \\\\\n\\midrule\n"
    label_map = {"exact_sequential|target": "Exact sequential, target",
                 "corr_scale_-1|target": "Corr.\\ scale $-1$, target",
                 "exact_sequential|joint": "Exact sequential, joint",
                 "mean_shift_2.0|target": "Mean shift $2\\tau$, target",
                 "var_ratio_4.0|target": "Variance ratio 4, target",
                 "corr_scale_-1|joint": "Corr.\\ scale $-1$, joint",
                 "collapse_intermediate|target": "Collapse intermediate, target"}
    verdict_map = {"NO_EXCESS_FLAGGED": "no excess flagged", "EXCESS_FLAGGED": "excess flagged",
                   "POWERED": "powered", "NOT_POWERED": "not powered"}
    for key, blk in cells.items():
        d = blk["detector"]
        t += (f"{label_map[key]} & {blk['role']} & {d['k']}/{d['n']} & {d['cp_lower_95_one_sided']:.3f} & "
              f"{d['cp_upper_95_one_sided']:.3f} & {verdict_map[blk['verdict']]} \\\\\n")
    t += "\\midrule\n"
    nc = cells["exact_sequential|target"]
    t += (f"Always-accept rule & null / alt. & 0/{nc['detector']['n']} & -- & -- & "
          f"{verdict_map[nc['negative_controls']['always_accept']]} / "
          f"{verdict_map[cells['mean_shift_2.0|target']['negative_controls']['always_accept']]} \\\\\n")
    t += (f"Always-reject rule & null & {nc['detector']['n']}/{nc['detector']['n']} & -- & -- & "
          f"{verdict_map[nc['negative_controls']['always_reject']]} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_e8.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Appendix: predicted vs observed (all cells)
    t = HEADER + "\\begin{tabular}{llrrrrrrr}\n\\toprule\n"
    t += ("Exp. & Condition & $M$ & $D_{\\mathrm{pop}}$ & $\\mathbb{E}[d]$ & $\\bar d$ [95\\% CI] & $z$ & "
          "$\\mathbb{E}[d_J]$ & $\\bar d_J$ \\\\\n & & & \\multicolumn{6}{c}{(all $\\times10^3$)} \\\\\n\\midrule\n")
    for r in pvo:
        oj = r.get("obs_dJ")
        z = r.get("z_obs_minus_pred")
        t += (f"{r['exp'].replace('P5-', '')} & {tt(r['cond'])} & {r['m']} & "
              f"{k3(r['pop_D_target'], 3)} & {k3(r['pred_E_d'], 3)} & {ci3(r['obs_d'])} & "
              f"{'NA' if z is None else f'{z:.2f}'} & {k3(r.get('pred_E_dJ'), 3)} & "
              f"{'--' if oj is None else k3(oj['mean'])} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_reanalysis.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Appendix: z-null check
    t = HEADER + "\\begin{tabular}{llrrrrr}\n\\toprule\n"
    t += ("Exp. & Condition & skew$(d)$ & kurt$(d)$ & $t_{\\mathrm{obs}}$ & sd of $t^\\ast$ & $q_{0.95}(t^\\ast)$ \\\\\n\\midrule\n")
    for z in znull["per_condition"]:
        t += (f"{z['exp'].replace('P5-', '')} & {tt(z['cond'])} & {z['skew_d']:.2f} & "
              f"{z['kurtosis_d']:.2f} & {z['t_obs']:.2f} & {z['signflip_t_sd']:.3f} & {z['signflip_t_q95']:.3f} \\\\\n")
    t += "\\bottomrule\n\\end{tabular}\n"
    with open(os.path.join(OUT, "tab_znull.tex"), "w") as f:
        f.write(t)

    # ------------------------------------------------------------------ Figure data
    mc = summ["P5-E5-MC"]["conditions"]
    sz = man["data"]["nonmarkov"]["scale_from_train"]["z"]
    tau2 = man["data"]["nonmarkov"]["true"]["tau2_z_given_x"]
    eabs = 2.0 / math.sqrt(math.pi) * math.sqrt(tau2) / sz
    lines = ["M floor lo hi theory"]
    pts = [(32, mc["null_m32"]), (64, mc["null_m64"]), (128, mc["null_m128"]),
           (256, summ["P5-E1-NULL"]["conditions"]["exact_sequential"]), (512, mc["null_m512"])]
    for m, s in pts:
        fl = s["target"]["ed_floor"]
        lines.append(f"{m} {fl['mean']:.6g} {fl['lo']:.6g} {fl['hi']:.6g} {2 * eabs / m:.6g}")
    open(os.path.join(OUT, "fig_mc.dat"), "w").write("\n".join(lines) + "\n")

    joint, rows_all = rows_for(cfg, man, "nonmarkov")
    tc = sp.true_conditionals(joint)
    rows100 = rows_all[:100]

    def pop_gap(n_steps, solver, w):
        dd, de = 0.0, 0.0
        for ex in rows100:
            L = an.pfode_branch_laws(tc, ex["x"], n_steps, solver, w)
            (mb, sb), (mc_, sc_), (me, se) = L["direct"], L["sequential"], L["exact"]
            dd += an.energy_distance_gauss(mb / sz, sb / sz, mc_ / sz, sc_ / sz)
            de += an.energy_distance_gauss(me / sz, se / sz, mb / sz, sb / sz)
        return dd / len(rows100), de / len(rows100)

    lines = ["steps euler_seq euler_bias heun_seq heun_bias"]
    for st_ in (2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 96, 128, 256):
        a, b = pop_gap(st_, "euler", 0.0)
        h1, h2 = pop_gap(st_, "heun", 0.0)
        lines.append(f"{st_} {a:.6g} {b:.6g} {h1:.6g} {h2:.6g}")
    open(os.path.join(OUT, "fig_solver_closed.dat"), "w").write("\n".join(lines) + "\n")
    lines = ["w seq bias"]
    for w in (0.0, 0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0):
        a, b = pop_gap(64, "euler", w)
        lines.append(f"{w} {a:.6g} {b:.6g}")
    open(os.path.join(OUT, "fig_cfg_closed.dat"), "w").write("\n".join(lines) + "\n")
    # one-sided 5% detection resolution of mean d at the E6/E7 design (N=100, M=256)
    res = 1.6449 * max(se_e6)
    with open(os.path.join(OUT, "numbers.tex"), "a") as f:
        f.write(macro("numResolution", f"{res:.5f}"))
    lines = ["x d lo hi"]
    for w, k in ((0.5, "cfg_0.5_seq"), (1.0, "cfg_1_seq"), (2.0, "cfg_2_seq"), (4.0, "cfg_4_seq")):
        s = c("P5-E7-CFG", k)["target"]["d"]
        lines.append(f"{w} {s['mean']:.6g} {s['lo']:.6g} {s['hi']:.6g}")
    open(os.path.join(OUT, "fig_cfg_obs.dat"), "w").write("\n".join(lines) + "\n")
    print("wrote", sorted(os.listdir(OUT)))



def write_reference_lines():
    """Horizontal reference line data (detection resolution) for the figure."""
    num = open(os.path.join(OUT, "numbers.tex")).read()
    res = float(num.split("\\numResolution}{")[1].split("}")[0])
    open(os.path.join(OUT, "fig_res_steps.dat"), "w").write(f"x y\n2 {res}\n256 {res}\n")
    open(os.path.join(OUT, "fig_res_w.dat"), "w").write(f"x y\n0 {res}\n4 {res}\n")


if __name__ == "__main__":
    main()
    write_reference_lines()
